brews:
  - git
  - python
  - atuin
  - age
  - uv
  - cloud-sql-proxy
  - sinelaw/fresh/fresh-editor
  - starship
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - rust

casks:
  - pycharm
  - whatsapp
  - iterm2
  - visual-studio-code
  - docker-desktop
  - postman
  - font-symbols-only-nerd-font
  - font-jetbrains-mono-nerd-font
