brews:
  - git
  - python
  - atuin
  - age
  - uv
  - sinelaw/fresh/fresh-editor
  - starship
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - rust
  - zoxide
  - commitizen
  - pre-commit
  - ghq
  - ruff

casks:
  - pycharm
  - iterm2
  - visual-studio-code
  - docker-desktop
  - postman
  - font-symbols-only-nerd-font
  - font-jetbrains-mono-nerd-font
  - notion
  - google-chrome
  - logi-options+
